name: CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        lfs: true
          #    - name: Git lfs pull
          #      working-directory: consensus-spec-tests
          #      run: git lfs pull
    - name: Install Rust
      run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Run formatter
      run: cargo fmt --check
    - name: Run clippy
      run: bash scripts/ci/clippy.bash
    - name: Run tests
      run: cargo test --release
